
def europa_valnames():
	return {'Amp Attack': ['number','amp_attack'],
'Amp Decay': ['number','amp_decay'],
'Amp Gain': ['number','amp_gain'],
'Amp Release': ['number','amp_release'],
'Amp Sustain': ['number','amp_sustain'],
'Amp Velocity': ['number','amp_velocity'],
'Comp Attack': ['number','comp_attack'],
'Comp On': ['number','comp_on'],
'Comp Ratio': ['number','comp_ratio'],
'Comp Release': ['number','comp_release'],
'Comp Threshold': ['number','comp_threshold'],
'Curve': ['string','curve'],
'Curve1': ['string','curve1'],
'Curve2': ['string','curve2'],
'Curve3': ['string','curve3'],
'Curve4': ['string','curve4'],
'Delay Amount': ['number','delay_amount'],
'Delay FB': ['number','delay_fb'],
'Delay On': ['number','delay_on'],
'Delay Pan': ['number','delay_pan'],
'Delay PingPong': ['number','delay_pingpong'],
'Delay Sync': ['number','delay_sync'],
'Delay Synced Time': ['number','delay_synced_time'],
'Delay Time': ['number','delay_time'],
'Dist Amount': ['number','dist_amount'],
'Dist Drive': ['number','dist_drive'],
'Dist On': ['number','dist_on'],
'Dist Tone': ['number','dist_tone'],
'Dist Type': ['number','dist_type'],
'Effect On': ['number','effect_on'],
'Effect Order': ['number','effect_order'],
'Effect Select': ['number','effect_select'],
'Env 1 Rate': ['number','env_1_rate'],
'Env 1 Syncrate': ['number','env_1_syncrate'],
'Env 2 Rate': ['number','env_2_rate'],
'Env 2 Syncrate': ['number','env_2_syncrate'],
'Env 3 Rate': ['number','env_3_rate'],
'Env 3 Syncrate': ['number','env_3_syncrate'],
'Env 4 Rate': ['number','env_4_rate'],
'Env 4 Syncrate': ['number','env_4_syncrate'],
'Env Edit Mode': ['number','env_edit_mode'],
'Env Select': ['number','env_select'],
'EQ Freq': ['number','eq_freq'],
'EQ Gain': ['number','eq_gain'],
'Eq On': ['number','eq_on'],
'EQ Q': ['number','eq_q'],
'Filter Drive': ['number','filter_drive'],
'Filter Freq': ['number','filter_freq'],
'Filter Kbd': ['number','filter_kbd'],
'Filter Mod': ['number','filter_mod'],
'Filter Mod Source': ['number','filter_mod_source'],
'Filter Reso': ['number','filter_reso'],
'Filter Type': ['number','filter_type'],
'Filter Vel': ['number','filter_vel'],
'Key Mode': ['number','key_mode'],
'LFO 1 Delay': ['number','lfo_1_delay'],
'LFO 1 Global': ['number','lfo_1_global'],
'LFO 1 KeySync': ['number','lfo_1_keysync'],
'LFO 1 Rate': ['number','lfo_1_rate'],
'LFO 1 SyncRate': ['number','lfo_1_syncrate'],
'LFO 1 TempoSync': ['number','lfo_1_temposync'],
'LFO 1 Wave': ['number','lfo_1_wave'],
'LFO 2 Delay': ['number','lfo_2_delay'],
'LFO 2 Global': ['number','lfo_2_global'],
'LFO 2 KeySync': ['number','lfo_2_keysync'],
'LFO 2 Rate': ['number','lfo_2_rate'],
'LFO 2 SyncRate': ['number','lfo_2_syncrate'],
'LFO 2 TempoSync': ['number','lfo_2_temposync'],
'LFO 2 Wave': ['number','lfo_2_wave'],
'LFO 3 Delay': ['number','lfo_3_delay'],
'LFO 3 Global': ['number','lfo_3_global'],
'LFO 3 KeySync': ['number','lfo_3_keysync'],
'LFO 3 Rate': ['number','lfo_3_rate'],
'LFO 3 SyncRate': ['number','lfo_3_syncrate'],
'LFO 3 TempoSync': ['number','lfo_3_temposync'],
'LFO 3 Wave': ['number','lfo_3_wave'],
'LFO Select': ['number','lfo_select'],
'Master Volume': ['number','master_volume'],
'Mod Effect Amount': ['number','mod_effect_amount'],
'Mod Effect Depth': ['number','mod_effect_depth'],
'Mod Effect Rate': ['number','mod_effect_rate'],
'Mod Effect Spread': ['number','mod_effect_spread'],
'Mod Effect Type': ['number','mod_effect_type'],
'mod_wheel': ['number','modwheel'],
'Mod1 Dest1': ['number','mod_1_dest1'],
'Mod1 Dest1 Amt': ['number','mod_1_dest1_amt'],
'Mod1 Dest2': ['number','mod_1_dest2'],
'Mod1 Dest2 Amt': ['number','mod_1_dest2_amt'],
'Mod1 Scale': ['number','mod_1_scale'],
'Mod1 Scale Amt': ['number','mod_1_scale_amt'],
'Mod1 Source': ['number','mod_1_source'],
'Mod2 Dest1': ['number','mod_2_dest1'],
'Mod2 Dest1 Amt': ['number','mod_2_dest1_amt'],
'Mod2 Dest2': ['number','mod_2_dest2'],
'Mod2 Dest2 Amt': ['number','mod_2_dest2_amt'],
'Mod2 Scale': ['number','mod_2_scale'],
'Mod2 Scale Amt': ['number','mod_2_scale_amt'],
'Mod2 Source': ['number','mod_2_source'],
'Mod3 Dest1': ['number','mod_3_dest1'],
'Mod3 Dest1 Amt': ['number','mod_3_dest1_amt'],
'Mod3 Dest2': ['number','mod_3_dest2'],
'Mod3 Dest2 Amt': ['number','mod_3_dest2_amt'],
'Mod3 Scale': ['number','mod_3_scale'],
'Mod3 Scale Amt': ['number','mod_3_scale_amt'],
'Mod3 Source': ['number','mod_3_source'],
'Mod4 Dest1': ['number','mod_4_dest1'],
'Mod4 Dest1 Amt': ['number','mod_4_dest1_amt'],
'Mod4 Dest2': ['number','mod_4_dest2'],
'Mod4 Dest2 Amt': ['number','mod_4_dest2_amt'],
'Mod4 Scale': ['number','mod_4_scale'],
'Mod4 Scale Amt': ['number','mod_4_scale_amt'],
'Mod4 Source': ['number','mod_4_source'],
'Mod5 Dest1': ['number','mod_5_dest1'],
'Mod5 Dest1 Amt': ['number','mod_5_dest1_amt'],
'Mod5 Dest2': ['number','mod_5_dest2'],
'Mod5 Dest2 Amt': ['number','mod_5_dest2_amt'],
'Mod5 Scale': ['number','mod_5_scale'],
'Mod5 Scale Amt': ['number','mod_5_scale_amt'],
'Mod5 Source': ['number','mod_5_source'],
'Mod6 Dest1': ['number','mod_6_dest1'],
'Mod6 Dest1 Amt': ['number','mod_6_dest1_amt'],
'Mod6 Dest2': ['number','mod_6_dest2'],
'Mod6 Dest2 Amt': ['number','mod_6_dest2_amt'],
'Mod6 Scale': ['number','mod_6_scale'],
'Mod6 Scale Amt': ['number','mod_6_scale_amt'],
'Mod6 Source': ['number','mod_6_source'],
'Mod7 Dest1': ['number','mod_7_dest1'],
'Mod7 Dest1 Amt': ['number','mod_7_dest1_amt'],
'Mod7 Dest2': ['number','mod_7_dest2'],
'Mod7 Dest2 Amt': ['number','mod_7_dest2_amt'],
'Mod7 Scale': ['number','mod_7_scale'],
'Mod7 Scale Amt': ['number','mod_7_scale_amt'],
'Mod7 Source': ['number','mod_7_source'],
'Mod8 Dest1': ['number','mod_8_dest1'],
'Mod8 Dest1 Amt': ['number','mod_8_dest1_amt'],
'Mod8 Dest2': ['number','mod_8_dest2'],
'Mod8 Dest2 Amt': ['number','mod_8_dest2_amt'],
'Mod8 Scale': ['number','mod_8_scale'],
'Mod8 Scale Amt': ['number','mod_8_scale_amt'],
'Mod8 Source': ['number','mod_8_source'],
'ModWheel CV Amount': ['number','modwheel_cv_amount'],
'Osc1 Blend': ['number','osc_1_blend'],
'Osc1 Count': ['number','osc_1_count'],
'Osc1 Detune': ['number','osc_1_detune'],
'Osc1 Filter': ['number','osc_1_filter'],
'Osc1 Filter Freq': ['number','osc_1_filter_freq'],
'Osc1 Filter Kbd': ['number','osc_1_filter_kbd'],
'Osc1 Filter Mod': ['number','osc_1_filter_mod'],
'Osc1 Filter On': ['number','osc_1_filter_on'],
'Osc1 Filter Reso': ['number','osc_1_filter_reso'],
'Osc1 Filter Source': ['number','osc_1_filter_source'],
'Osc1 Filter Vel': ['number','osc_1_filter_vel'],
'Osc1 Harm': ['number','osc_1_harm'],
'Osc1 Harm Amt': ['number','osc_1_harm_amt'],
'Osc1 Harm On': ['number','osc_1_harm_on'],
'Osc1 Harm Pos': ['number','osc_1_harm_pos'],
'Osc1 Level': ['number','osc_1_level'],
'Osc1 Mod1': ['number','osc_1_mod1'],
'Osc1 Mod1 Amt': ['number','osc_1_mod1_amt'],
'Osc1 Mod1 Mod': ['number','osc_1_mod1_mod'],
'Osc1 Mod1 On': ['number','osc_1_mod1_on'],
'Osc1 Mod1 Source': ['number','osc_1_mod1_source'],
'Osc1 Mod2': ['number','osc_1_mod2'],
'Osc1 Mod2 Amt': ['number','osc_1_mod2_amt'],
'Osc1 Mod2 Mod': ['number','osc_1_mod2_mod'],
'Osc1 Mod2 On': ['number','osc_1_mod2_on'],
'Osc1 Mod2 Source': ['number','osc_1_mod2_source'],
'Osc1 Oct': ['number','osc_1_oct'],
'Osc1 On': ['number','osc_1_on'],
'Osc1 Pan': ['number','osc_1_pan'],
'Osc1 Pitch Kbd': ['number','osc_1_pitch_kbd'],
'Osc1 Semi': ['number','osc_1_semi'],
'Osc1 Shape': ['number','osc_1_shape'],
'Osc1 Shape Amt': ['number','osc_1_shape_amt'],
'Osc1 Shape Source': ['number','osc_1_shape_source'],
'Osc1 Shape Vel': ['number','osc_1_shape_vel'],
'Osc1 Spread': ['number','osc_1_spread'],
'Osc1 SyncPhase': ['number','osc_1_syncphase'],
'Osc1 To Filter': ['number','osc_1_to_filter'],
'Osc1 Tune': ['number','osc_1_tune'],
'Osc1 Unison Mode': ['number','osc_1_unison_mode'],
'Osc1 Unison On': ['number','osc_1_unison_on'],
'Osc1 Wave': ['number','osc_1_wave'],
'Osc2 Blend': ['number','osc_2_blend'],
'Osc2 Count': ['number','osc_2_count'],
'Osc2 Detune': ['number','osc_2_detune'],
'Osc2 Filter': ['number','osc_2_filter'],
'Osc2 Filter Freq': ['number','osc_2_filter_freq'],
'Osc2 Filter Kbd': ['number','osc_2_filter_kbd'],
'Osc2 Filter Mod': ['number','osc_2_filter_mod'],
'Osc2 Filter On': ['number','osc_2_filter_on'],
'Osc2 Filter Reso': ['number','osc_2_filter_reso'],
'Osc2 Filter Source': ['number','osc_2_filter_source'],
'Osc2 Filter Vel': ['number','osc_2_filter_vel'],
'Osc2 Harm': ['number','osc_2_harm'],
'Osc2 Harm Amt': ['number','osc_2_harm_amt'],
'Osc2 Harm On': ['number','osc_2_harm_on'],
'Osc2 Harm Pos': ['number','osc_2_harm_pos'],
'Osc2 Level': ['number','osc_2_level'],
'Osc2 Mod1': ['number','osc_2_mod1'],
'Osc2 Mod1 Amt': ['number','osc_2_mod1_amt'],
'Osc2 Mod1 Mod': ['number','osc_2_mod1_mod'],
'Osc2 Mod1 On': ['number','osc_2_mod1_on'],
'Osc2 Mod1 Source': ['number','osc_2_mod1_source'],
'Osc2 Mod2': ['number','osc_2_mod2'],
'Osc2 Mod2 Amt': ['number','osc_2_mod2_amt'],
'Osc2 Mod2 Mod': ['number','osc_2_mod2_mod'],
'Osc2 Mod2 On': ['number','osc_2_mod2_on'],
'Osc2 Mod2 Source': ['number','osc_2_mod2_source'],
'Osc2 Oct': ['number','osc_2_oct'],
'Osc2 On': ['number','osc_2_on'],
'Osc2 Pan': ['number','osc_2_pan'],
'Osc2 Pitch Kbd': ['number','osc_2_pitch_kbd'],
'Osc2 Semi': ['number','osc_2_semi'],
'Osc2 Shape': ['number','osc_2_shape'],
'Osc2 Shape Amt': ['number','osc_2_shape_amt'],
'Osc2 Shape Source': ['number','osc_2_shape_source'],
'Osc2 Shape Vel': ['number','osc_2_shape_vel'],
'Osc2 Spread': ['number','osc_2_spread'],
'Osc2 SyncPhase': ['number','osc_2_syncphase'],
'Osc2 To Filter': ['number','osc_2_to_filter'],
'Osc2 Tune': ['number','osc_2_tune'],
'Osc2 Unison Mode': ['number','osc_2_unison_mode'],
'Osc2 Unison On': ['number','osc_2_unison_on'],
'Osc2 Wave': ['number','osc_2_wave'],
'Osc3 Blend': ['number','osc_3_blend'],
'Osc3 Count': ['number','osc_3_count'],
'Osc3 Detune': ['number','osc_3_detune'],
'Osc3 Filter': ['number','osc_3_filter'],
'Osc3 Filter Freq': ['number','osc_3_filter_freq'],
'Osc3 Filter Kbd': ['number','osc_3_filter_kbd'],
'Osc3 Filter Mod': ['number','osc_3_filter_mod'],
'Osc3 Filter On': ['number','osc_3_filter_on'],
'Osc3 Filter Reso': ['number','osc_3_filter_reso'],
'Osc3 Filter Source': ['number','osc_3_filter_source'],
'Osc3 Filter Vel': ['number','osc_3_filter_vel'],
'Osc3 Harm': ['number','osc_3_harm'],
'Osc3 Harm Amt': ['number','osc_3_harm_amt'],
'Osc3 Harm On': ['number','osc_3_harm_on'],
'Osc3 Harm Pos': ['number','osc_3_harm_pos'],
'Osc3 Level': ['number','osc_3_level'],
'Osc3 Mod1': ['number','osc_3_mod1'],
'Osc3 Mod1 Amt': ['number','osc_3_mod1_amt'],
'Osc3 Mod1 Mod': ['number','osc_3_mod1_mod'],
'Osc3 Mod1 On': ['number','osc_3_mod1_on'],
'Osc3 Mod1 Source': ['number','osc_3_mod1_source'],
'Osc3 Mod2': ['number','osc_3_mod2'],
'Osc3 Mod2 Amt': ['number','osc_3_mod2_amt'],
'Osc3 Mod2 Mod': ['number','osc_3_mod2_mod'],
'Osc3 Mod2 On': ['number','osc_3_mod2_on'],
'Osc3 Mod2 Source': ['number','osc_3_mod2_source'],
'Osc3 Oct': ['number','osc_3_oct'],
'Osc3 On': ['number','osc_3_on'],
'Osc3 Pan': ['number','osc_3_pan'],
'Osc3 Pitch Kbd': ['number','osc_3_pitch_kbd'],
'Osc3 Semi': ['number','osc_3_semi'],
'Osc3 Shape': ['number','osc_3_shape'],
'Osc3 Shape Amt': ['number','osc_3_shape_amt'],
'Osc3 Shape Source': ['number','osc_3_shape_source'],
'Osc3 Shape Vel': ['number','osc_3_shape_vel'],
'Osc3 Spread': ['number','osc_3_spread'],
'Osc3 SyncPhase': ['number','osc_3_syncphase'],
'Osc3 To Filter': ['number','osc_3_to_filter'],
'Osc3 Tune': ['number','osc_3_tune'],
'Osc3 Unison Mode': ['number','osc_3_unison_mode'],
'Osc3 Unison On': ['number','osc_3_unison_on'],
'Osc3 Wave': ['number','osc_3_wave'],
'OscSel': ['number','osc_sel'],
'Pan': ['number','pan'],
'Phaser On': ['number','phaser_on'],
'PitchBend CV Amount': ['number','pitchbend_cv_amount'],
'Pitchbend Range': ['number','pitchbend_range'],
'Portamento': ['number','portamento'],
'Portamento Mode': ['number','portamento_mode'],
'Reverb Amount': ['number','reverb_amount'],
'Reverb Damp': ['number','reverb_damp'],
'Reverb Decay': ['number','reverb_decay'],
'Reverb On': ['number','reverb_on'],
'Reverb Size': ['number','reverb_size'],
'Voices': ['number','voices']}